spring.application.name=EvershineServer
# Sets your default active profile to local development
spring.profiles.active=dev

# --- SWAGGER & OPENAPI CONFIGURATION ---
# Sets the JSON documentation endpoint to http://localhost:8080/api-docs
springdoc.api-docs.path=/api-docs

# Sets your interactive browser dashboard to http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

server.port=${PORT:8080}