# --- DATABASE CONFIGURATION FOR PRODUCTION ---
spring.datasource.url=jdbc:mysql://${PROD_DB_HOST:localhost}:${PROD_DB_PORT:3306}/${PROD_DB_NAME:evershine_db}?useSSL=true&serverTimezone=UTC
spring.datasource.username=${PROD_DB_USERNAME}
spring.datasource.password=${PROD_DB_PASSWORD}

# --- HIBERNATE SECURITY SETTINGS ---
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 'validate' safely prevents altering tables on your production instance, letter change it to 'none'
spring.jpa.hibernate.ddl-auto=update

# Performance Optimization: Turns off heavy console log printing
spring.jpa.show-sql=false
