# --- DATABASE CONFIGURATION FOR PRODUCTION ---
spring.datasource.url=jdbc:mysql://3DqN4FFE9tBEX83.root:HBq7wSE4f5rAVVCp@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/evershine_db?sslMode=VERIFY_IDENTITY
spring.datasource.username=${PROD_DB_USERNAME}
spring.datasource.password=${PROD_DB_PASSWORD}

# --- HIBERNATE SECURITY SETTINGS ---
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 'validate' safely prevents altering tables on your production instance, letter change it to 'none'
spring.jpa.hibernate.ddl-auto=update

# Performance Optimization: Turns off heavy console log printing
spring.jpa.show-sql=false
